# Data paths
data:
  images_dir: "datasets/ultrasound/image"
  annotations_dir: "datasets/ultrasound/annotations"
  processed_images_dir: "datasets/ultrasound/processed_images"
  processed_annotations_dir: "datasets/ultrasound/processed_annotations"
  metadata_dir: "datasets/ultrasound"

# Model parameters
model:
  swin_model: "microsoft/swin-tiny-patch4-window7-224"
  num_classes: 2  # Thoracic, Lumbar
  num_clusters: 3  # Left, Right, Center
  gnn_hidden_dim: 128
  gnn_num_layers: 2

# Training parameters
training:
  batch_size: 4
  num_epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.01
  early_stopping_patience: 5
  detection_loss_weight: 1.0
  clustering_loss_weight: 0.1
  checkpoint_dir: "outputs/checkpoints"
  log_dir: "outputs/logs"

# Data preprocessing
preprocessing:
  image_size: [512, 256]  # Height, Width (adjust based on your images)
  clahe_clip_limit: 2.0
  clahe_tile_grid_size: [8, 8]
  despeckle_h: 10

# Data augmentation
augmentation:
  speckle_noise_std: 0.05
  elastic_alpha: 50
  elastic_sigma: 5
  contrast_range: [0.8, 1.2]
  brightness_range: [0.9, 1.1]

# Evaluation
evaluation:
  val_split: 0.15
  iou_threshold: 0.5